name = "glimt"
version = "0.5.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
description = "A Gleam library for logging"
repository = { type = "github", user = "JohnBjrk", repo = "glimt" }

gleam_version = ">= 1.0.0"

[dependencies]
gleam_stdlib = "~> 0.36"
gleam_erlang = "~> 0.24"
gleam_otp = "~> 0.10"
birl = "~> 1.5"
gleam_json = "~> 1.0"
gleam_community_ansi = "~> 1.4"

[dev-dependencies]
showtime = "~> 0.2"
gleam_http = "~> 3.1"
