name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: erlef/setup-beam@v1.15.0
        with:
          otp-version: "26.1.2"
          gleam-version: "1.0.0"
          rebar3-version: "3"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
